package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsBalancoEnergiaDessemEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsBalancoEnergiaDessemEntityAllPropertiesEquals(
        OnsBalancoEnergiaDessemEntity expected,
        OnsBalancoEnergiaDessemEntity actual
    ) {
        assertOnsBalancoEnergiaDessemEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsBalancoEnergiaDessemEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsBalancoEnergiaDessemEntityAllUpdatablePropertiesEquals(
        OnsBalancoEnergiaDessemEntity expected,
        OnsBalancoEnergiaDessemEntity actual
    ) {
        assertOnsBalancoEnergiaDessemEntityUpdatableFieldsEquals(expected, actual);
        assertOnsBalancoEnergiaDessemEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsBalancoEnergiaDessemEntityAutoGeneratedPropertiesEquals(
        OnsBalancoEnergiaDessemEntity expected,
        OnsBalancoEnergiaDessemEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsBalancoEnergiaDessemEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsBalancoEnergiaDessemEntityUpdatableFieldsEquals(
        OnsBalancoEnergiaDessemEntity expected,
        OnsBalancoEnergiaDessemEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsBalancoEnergiaDessemEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getValDemanda()).as("check valDemanda").isEqualTo(expected.getValDemanda()))
            .satisfies(a ->
                assertThat(a.getValGeracaohidraulicamwmed())
                    .as("check valGeracaohidraulicamwmed")
                    .isEqualTo(expected.getValGeracaohidraulicamwmed())
            )
            .satisfies(a -> assertThat(a.getValGeracaopchmwmed()).as("check valGeracaopchmwmed").isEqualTo(expected.getValGeracaopchmwmed())
            )
            .satisfies(a ->
                assertThat(a.getValGeracaotermicamwed()).as("check valGeracaotermicamwed").isEqualTo(expected.getValGeracaotermicamwed())
            )
            .satisfies(a -> assertThat(a.getValGeracaopctmwmed()).as("check valGeracaopctmwmed").isEqualTo(expected.getValGeracaopctmwmed())
            )
            .satisfies(a ->
                assertThat(a.getValGeracaoeolicamwmed()).as("check valGeracaoeolicamwmed").isEqualTo(expected.getValGeracaoeolicamwmed())
            )
            .satisfies(a ->
                assertThat(a.getValGeracaofotovoltaicamwmed())
                    .as("check valGeracaofotovoltaicamwmed")
                    .isEqualTo(expected.getValGeracaofotovoltaicamwmed())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsBalancoEnergiaDessemEntityUpdatableRelationshipsEquals(
        OnsBalancoEnergiaDessemEntity expected,
        OnsBalancoEnergiaDessemEntity actual
    ) {
        // empty method
    }
}
