package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsCargaEnergiaMensalEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaMensalEntityAllPropertiesEquals(
        OnsCargaEnergiaMensalEntity expected,
        OnsCargaEnergiaMensalEntity actual
    ) {
        assertOnsCargaEnergiaMensalEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsCargaEnergiaMensalEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaMensalEntityAllUpdatablePropertiesEquals(
        OnsCargaEnergiaMensalEntity expected,
        OnsCargaEnergiaMensalEntity actual
    ) {
        assertOnsCargaEnergiaMensalEntityUpdatableFieldsEquals(expected, actual);
        assertOnsCargaEnergiaMensalEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaMensalEntityAutoGeneratedPropertiesEquals(
        OnsCargaEnergiaMensalEntity expected,
        OnsCargaEnergiaMensalEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCargaEnergiaMensalEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaMensalEntityUpdatableFieldsEquals(
        OnsCargaEnergiaMensalEntity expected,
        OnsCargaEnergiaMensalEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCargaEnergiaMensalEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a ->
                assertThat(a.getValCargaenergiamwmed()).as("check valCargaenergiamwmed").isEqualTo(expected.getValCargaenergiamwmed())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaMensalEntityUpdatableRelationshipsEquals(
        OnsCargaEnergiaMensalEntity expected,
        OnsCargaEnergiaMensalEntity actual
    ) {
        // empty method
    }
}
