package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsCurvaCargaHorariaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCurvaCargaHorariaEntityAllPropertiesEquals(
        OnsCurvaCargaHorariaEntity expected,
        OnsCurvaCargaHorariaEntity actual
    ) {
        assertOnsCurvaCargaHorariaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsCurvaCargaHorariaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCurvaCargaHorariaEntityAllUpdatablePropertiesEquals(
        OnsCurvaCargaHorariaEntity expected,
        OnsCurvaCargaHorariaEntity actual
    ) {
        assertOnsCurvaCargaHorariaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsCurvaCargaHorariaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCurvaCargaHorariaEntityAutoGeneratedPropertiesEquals(
        OnsCurvaCargaHorariaEntity expected,
        OnsCurvaCargaHorariaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCurvaCargaHorariaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCurvaCargaHorariaEntityUpdatableFieldsEquals(
        OnsCurvaCargaHorariaEntity expected,
        OnsCurvaCargaHorariaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCurvaCargaHorariaEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a ->
                assertThat(a.getValCargaenergiahomwmed()).as("check valCargaenergiahomwmed").isEqualTo(expected.getValCargaenergiahomwmed())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCurvaCargaHorariaEntityUpdatableRelationshipsEquals(
        OnsCurvaCargaHorariaEntity expected,
        OnsCurvaCargaHorariaEntity actual
    ) {
        // empty method
    }
}
