package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsCmoSemihorarioEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCmoSemihorarioEntityAllPropertiesEquals(OnsCmoSemihorarioEntity expected, OnsCmoSemihorarioEntity actual) {
        assertOnsCmoSemihorarioEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsCmoSemihorarioEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCmoSemihorarioEntityAllUpdatablePropertiesEquals(
        OnsCmoSemihorarioEntity expected,
        OnsCmoSemihorarioEntity actual
    ) {
        assertOnsCmoSemihorarioEntityUpdatableFieldsEquals(expected, actual);
        assertOnsCmoSemihorarioEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCmoSemihorarioEntityAutoGeneratedPropertiesEquals(
        OnsCmoSemihorarioEntity expected,
        OnsCmoSemihorarioEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCmoSemihorarioEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCmoSemihorarioEntityUpdatableFieldsEquals(
        OnsCmoSemihorarioEntity expected,
        OnsCmoSemihorarioEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCmoSemihorarioEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getValCmo()).as("check valCmo").isEqualTo(expected.getValCmo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCmoSemihorarioEntityUpdatableRelationshipsEquals(
        OnsCmoSemihorarioEntity expected,
        OnsCmoSemihorarioEntity actual
    ) {
        // empty method
    }
}
