package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsCargaEnergiaVerificadaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaVerificadaEntityAllPropertiesEquals(
        OnsCargaEnergiaVerificadaEntity expected,
        OnsCargaEnergiaVerificadaEntity actual
    ) {
        assertOnsCargaEnergiaVerificadaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsCargaEnergiaVerificadaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaVerificadaEntityAllUpdatablePropertiesEquals(
        OnsCargaEnergiaVerificadaEntity expected,
        OnsCargaEnergiaVerificadaEntity actual
    ) {
        assertOnsCargaEnergiaVerificadaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsCargaEnergiaVerificadaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaVerificadaEntityAutoGeneratedPropertiesEquals(
        OnsCargaEnergiaVerificadaEntity expected,
        OnsCargaEnergiaVerificadaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCargaEnergiaVerificadaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaVerificadaEntityUpdatableFieldsEquals(
        OnsCargaEnergiaVerificadaEntity expected,
        OnsCargaEnergiaVerificadaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsCargaEnergiaVerificadaEntity relevant properties")
            .satisfies(a -> assertThat(a.getCodAreacarga()).as("check codAreacarga").isEqualTo(expected.getCodAreacarga()))
            .satisfies(a -> assertThat(a.getDatReferencia()).as("check datReferencia").isEqualTo(expected.getDatReferencia()))
            .satisfies(a -> assertThat(a.getDinReferenciautc()).as("check dinReferenciautc").isEqualTo(expected.getDinReferenciautc()))
            .satisfies(a -> assertThat(a.getValCargaglobal()).as("check valCargaglobal").isEqualTo(expected.getValCargaglobal()))
            .satisfies(a -> assertThat(a.getValCargaglobalsmmg()).as("check valCargaglobalsmmg").isEqualTo(expected.getValCargaglobalsmmg())
            )
            .satisfies(a -> assertThat(a.getValCargammgd()).as("check valCargammgd").isEqualTo(expected.getValCargammgd()))
            .satisfies(a -> assertThat(a.getValCargaglobalcons()).as("check valCargaglobalcons").isEqualTo(expected.getValCargaglobalcons())
            )
            .satisfies(a -> assertThat(a.getValConsistencia()).as("check valConsistencia").isEqualTo(expected.getValConsistencia()))
            .satisfies(a ->
                assertThat(a.getValCargasupervisionada()).as("check valCargasupervisionada").isEqualTo(expected.getValCargasupervisionada())
            )
            .satisfies(a ->
                assertThat(a.getValCarganaosupervisionada())
                    .as("check valCarganaosupervisionada")
                    .isEqualTo(expected.getValCarganaosupervisionada())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsCargaEnergiaVerificadaEntityUpdatableRelationshipsEquals(
        OnsCargaEnergiaVerificadaEntity expected,
        OnsCargaEnergiaVerificadaEntity actual
    ) {
        // empty method
    }
}
