package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityAllPropertiesEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity actual
    ) {
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityAllUpdatablePropertiesEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity actual
    ) {
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityAutoGeneratedPropertiesEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityUpdatableFieldsEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a ->
                assertThat(a.getNomModalidadeoperacao()).as("check nomModalidadeoperacao").isEqualTo(expected.getNomModalidadeoperacao())
            )
            .satisfies(a -> assertThat(a.getIdEstado()).as("check idEstado").isEqualTo(expected.getIdEstado()))
            .satisfies(a -> assertThat(a.getNomConjuntousina()).as("check nomConjuntousina").isEqualTo(expected.getNomConjuntousina()))
            .satisfies(a -> assertThat(a.getNomUsina()).as("check nomUsina").isEqualTo(expected.getNomUsina()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getIdOns()).as("check idOns").isEqualTo(expected.getIdOns()))
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()))
            .satisfies(a -> assertThat(a.getValVentoverificado()).as("check valVentoverificado").isEqualTo(expected.getValVentoverificado())
            )
            .satisfies(a ->
                assertThat(a.getFlgDadoventoinvalido()).as("check flgDadoventoinvalido").isEqualTo(expected.getFlgDadoventoinvalido())
            )
            .satisfies(a -> assertThat(a.getValGeracaoestimada()).as("check valGeracaoestimada").isEqualTo(expected.getValGeracaoestimada())
            )
            .satisfies(a ->
                assertThat(a.getValGeracaoverificada()).as("check valGeracaoverificada").isEqualTo(expected.getValGeracaoverificada())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntityUpdatableRelationshipsEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasDetalhamentoUsinasEntity actual
    ) {
        // empty method
    }
}
