package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosRelacionamentoEntreConjuntosEUsinasEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityAllPropertiesEquals(
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity expected,
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity actual
    ) {
        assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityAllUpdatablePropertiesEquals(
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity expected,
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity actual
    ) {
        assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityAutoGeneratedPropertiesEquals(
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity expected,
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRelacionamentoEntreConjuntosEUsinasEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityUpdatableFieldsEquals(
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity expected,
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRelacionamentoEntreConjuntosEUsinasEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getEstadId()).as("check estadId").isEqualTo(expected.getEstadId()))
            .satisfies(a -> assertThat(a.getNomEstado()).as("check nomEstado").isEqualTo(expected.getNomEstado()))
            .satisfies(a -> assertThat(a.getIdTipousina()).as("check idTipousina").isEqualTo(expected.getIdTipousina()))
            .satisfies(a -> assertThat(a.getIdConjuntousina()).as("check idConjuntousina").isEqualTo(expected.getIdConjuntousina()))
            .satisfies(a -> assertThat(a.getIdOnsConjunto()).as("check idOnsConjunto").isEqualTo(expected.getIdOnsConjunto()))
            .satisfies(a -> assertThat(a.getIdOnsUsina()).as("check idOnsUsina").isEqualTo(expected.getIdOnsUsina()))
            .satisfies(a -> assertThat(a.getNomConjunto()).as("check nomConjunto").isEqualTo(expected.getNomConjunto()))
            .satisfies(a -> assertThat(a.getNomUsina()).as("check nomUsina").isEqualTo(expected.getNomUsina()))
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()))
            .satisfies(a ->
                assertThat(a.getDatIniciorelacionamento())
                    .as("check datIniciorelacionamento")
                    .isEqualTo(expected.getDatIniciorelacionamento())
            )
            .satisfies(a ->
                assertThat(a.getDatFimrelacionamento()).as("check datFimrelacionamento").isEqualTo(expected.getDatFimrelacionamento())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreConjuntosEUsinasEntityUpdatableRelationshipsEquals(
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity expected,
        OnsDadosRelacionamentoEntreConjuntosEUsinasEntity actual
    ) {
        // empty method
    }
}
