package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityAllPropertiesEquals(
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity expected,
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity actual
    ) {
        assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityAllUpdatablePropertiesEquals(
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity expected,
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity actual
    ) {
        assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityAutoGeneratedPropertiesEquals(
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity expected,
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityUpdatableFieldsEquals(
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity expected,
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity relevant properties")
            .satisfies(a -> assertThat(a.getDatProgramacao()).as("check datProgramacao").isEqualTo(expected.getDatProgramacao()))
            .satisfies(a -> assertThat(a.getNumPatamar()).as("check numPatamar").isEqualTo(expected.getNumPatamar()))
            .satisfies(a -> assertThat(a.getCodUsinapdp()).as("check codUsinapdp").isEqualTo(expected.getCodUsinapdp()))
            .satisfies(a -> assertThat(a.getNomUsinapdp()).as("check nomUsinapdp").isEqualTo(expected.getNomUsinapdp()))
            .satisfies(a -> assertThat(a.getValPrevisao()).as("check valPrevisao").isEqualTo(expected.getValPrevisao()))
            .satisfies(a -> assertThat(a.getValProgramado()).as("check valProgramado").isEqualTo(expected.getValProgramado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntityUpdatableRelationshipsEquals(
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity expected,
        OnsDadosValoresPrevisaoVersusProgramadoEolicasESolaresEntity actual
    ) {
        // empty method
    }
}
