package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosHidraulicosReservatorioBaseHorariaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHidraulicosReservatorioBaseHorariaEntityAllPropertiesEquals(
        OnsDadosHidraulicosReservatorioBaseHorariaEntity expected,
        OnsDadosHidraulicosReservatorioBaseHorariaEntity actual
    ) {
        assertOnsDadosHidraulicosReservatorioBaseHorariaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosHidraulicosReservatorioBaseHorariaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHidraulicosReservatorioBaseHorariaEntityAllUpdatablePropertiesEquals(
        OnsDadosHidraulicosReservatorioBaseHorariaEntity expected,
        OnsDadosHidraulicosReservatorioBaseHorariaEntity actual
    ) {
        assertOnsDadosHidraulicosReservatorioBaseHorariaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosHidraulicosReservatorioBaseHorariaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHidraulicosReservatorioBaseHorariaEntityAutoGeneratedPropertiesEquals(
        OnsDadosHidraulicosReservatorioBaseHorariaEntity expected,
        OnsDadosHidraulicosReservatorioBaseHorariaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosHidraulicosReservatorioBaseHorariaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHidraulicosReservatorioBaseHorariaEntityUpdatableFieldsEquals(
        OnsDadosHidraulicosReservatorioBaseHorariaEntity expected,
        OnsDadosHidraulicosReservatorioBaseHorariaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosHidraulicosReservatorioBaseHorariaEntity relevant properties")
            .satisfies(a -> assertThat(a.getValVolumeutil()).as("check valVolumeutil").isEqualTo(expected.getValVolumeutil()))
            .satisfies(a -> assertThat(a.getValVazaoafluente()).as("check valVazaoafluente").isEqualTo(expected.getValVazaoafluente()))
            .satisfies(a -> assertThat(a.getValVazaodefluente()).as("check valVazaodefluente").isEqualTo(expected.getValVazaodefluente()))
            .satisfies(a -> assertThat(a.getValVazaoturbinada()).as("check valVazaoturbinada").isEqualTo(expected.getValVazaoturbinada()))
            .satisfies(a -> assertThat(a.getValVazaovertida()).as("check valVazaovertida").isEqualTo(expected.getValVazaovertida()))
            .satisfies(a ->
                assertThat(a.getValVazaooutrasestruturas())
                    .as("check valVazaooutrasestruturas")
                    .isEqualTo(expected.getValVazaooutrasestruturas())
            )
            .satisfies(a ->
                assertThat(a.getValVazaotransferida()).as("check valVazaotransferida").isEqualTo(expected.getValVazaotransferida())
            )
            .satisfies(a ->
                assertThat(a.getValVazaovertidanaoturbinavel())
                    .as("check valVazaovertidanaoturbinavel")
                    .isEqualTo(expected.getValVazaovertidanaoturbinavel())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHidraulicosReservatorioBaseHorariaEntityUpdatableRelationshipsEquals(
        OnsDadosHidraulicosReservatorioBaseHorariaEntity expected,
        OnsDadosHidraulicosReservatorioBaseHorariaEntity actual
    ) {
        // empty method
    }
}
