package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityAllPropertiesEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity actual
    ) {
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityAllUpdatablePropertiesEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity actual
    ) {
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityAutoGeneratedPropertiesEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityUpdatableFieldsEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getIdEstado()).as("check idEstado").isEqualTo(expected.getIdEstado()))
            .satisfies(a -> assertThat(a.getNomEstado()).as("check nomEstado").isEqualTo(expected.getNomEstado()))
            .satisfies(a -> assertThat(a.getNomUsina()).as("check nomUsina").isEqualTo(expected.getNomUsina()))
            .satisfies(a -> assertThat(a.getIdOns()).as("check idOns").isEqualTo(expected.getIdOns()))
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getValGeracao()).as("check valGeracao").isEqualTo(expected.getValGeracao()))
            .satisfies(a -> assertThat(a.getValGeracaolimitada()).as("check valGeracaolimitada").isEqualTo(expected.getValGeracaolimitada())
            )
            .satisfies(a -> assertThat(a.getValDisponibilidade()).as("check valDisponibilidade").isEqualTo(expected.getValDisponibilidade())
            )
            .satisfies(a ->
                assertThat(a.getValGeracaoreferencia()).as("check valGeracaoreferencia").isEqualTo(expected.getValGeracaoreferencia())
            )
            .satisfies(a ->
                assertThat(a.getValGeracaoreferenciafinal())
                    .as("check valGeracaoreferenciafinal")
                    .isEqualTo(expected.getValGeracaoreferenciafinal())
            )
            .satisfies(a -> assertThat(a.getCodRazaorestricao()).as("check codRazaorestricao").isEqualTo(expected.getCodRazaorestricao()))
            .satisfies(a -> assertThat(a.getCodOrigemrestricao()).as("check codOrigemrestricao").isEqualTo(expected.getCodOrigemrestricao())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntityUpdatableRelationshipsEquals(
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity expected,
        OnsDadosRestricaoOperacaoConstrainedoffUsinasEolicasEntity actual
    ) {
        // empty method
    }
}
