package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityAllPropertiesEquals(
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity expected,
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity actual
    ) {
        assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityAllUpdatablePropertiesEquals(
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity expected,
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity actual
    ) {
        assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityAutoGeneratedPropertiesEquals(
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity expected,
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityUpdatableFieldsEquals(
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity expected,
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity relevant properties")
            .satisfies(a -> assertThat(a.getDscAgregacao()).as("check dscAgregacao").isEqualTo(expected.getDscAgregacao()))
            .satisfies(a -> assertThat(a.getDscCaracteristica()).as("check dscCaracteristica").isEqualTo(expected.getDscCaracteristica()))
            .satisfies(a -> assertThat(a.getDinReferencia()).as("check dinReferencia").isEqualTo(expected.getDinReferencia()))
            .satisfies(a -> assertThat(a.getNumNprcConcluidas()).as("check numNprcConcluidas").isEqualTo(expected.getNumNprcConcluidas()))
            .satisfies(a -> assertThat(a.getNumNprpProgramadas()).as("check numNprpProgramadas").isEqualTo(expected.getNumNprpProgramadas())
            )
            .satisfies(a -> assertThat(a.getNumNpratAtrasadas()).as("check numNpratAtrasadas").isEqualTo(expected.getNumNpratAtrasadas()))
            .satisfies(a -> assertThat(a.getNumNpraAntecipadas()).as("check numNpraAntecipadas").isEqualTo(expected.getNumNpraAntecipadas())
            )
            .satisfies(a ->
                assertThat(a.getNumNprcpConcluidasPrazo())
                    .as("check numNprcpConcluidasPrazo")
                    .isEqualTo(expected.getNumNprcpConcluidasPrazo())
            )
            .satisfies(a -> assertThat(a.getValEcpa()).as("check valEcpa").isEqualTo(expected.getValEcpa()))
            .satisfies(a -> assertThat(a.getValPcpa()).as("check valPcpa").isEqualTo(expected.getValPcpa()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntityUpdatableRelationshipsEquals(
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity expected,
        OnsDadosIndicadoresCumprimentoProvidenciasEcpaEPcpaEntity actual
    ) {
        // empty method
    }
}
