package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityAllPropertiesEquals(
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity expected,
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity actual
    ) {
        assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityAllUpdatablePropertiesEquals(
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity expected,
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity actual
    ) {
        assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityAutoGeneratedPropertiesEquals(
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity expected,
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityUpdatableFieldsEquals(
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity expected,
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getEstadId()).as("check estadId").isEqualTo(expected.getEstadId()))
            .satisfies(a -> assertThat(a.getNomEstado()).as("check nomEstado").isEqualTo(expected.getNomEstado()))
            .satisfies(a -> assertThat(a.getIdTipousina()).as("check idTipousina").isEqualTo(expected.getIdTipousina()))
            .satisfies(a ->
                assertThat(a.getIdOnsPequenasusinas()).as("check idOnsPequenasusinas").isEqualTo(expected.getIdOnsPequenasusinas())
            )
            .satisfies(a -> assertThat(a.getIdOnsUsina()).as("check idOnsUsina").isEqualTo(expected.getIdOnsUsina()))
            .satisfies(a -> assertThat(a.getNomPequenasusinas()).as("check nomPequenasusinas").isEqualTo(expected.getNomPequenasusinas()))
            .satisfies(a -> assertThat(a.getNomUsina()).as("check nomUsina").isEqualTo(expected.getNomUsina()))
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntityUpdatableRelationshipsEquals(
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity expected,
        OnsDadosRelacionamentoEntreGruposPequenasUsinasEUsinasEntity actual
    ) {
        // empty method
    }
}
