package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityAllPropertiesEquals(
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity expected,
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity actual
    ) {
        assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityAllUpdatablePropertiesEquals(
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity expected,
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity actual
    ) {
        assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityAutoGeneratedPropertiesEquals(
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity expected,
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityUpdatableFieldsEquals(
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity expected,
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity relevant properties")
            .satisfies(a -> assertThat(a.getDatPdp()).as("check datPdp").isEqualTo(expected.getDatPdp()))
            .satisfies(a -> assertThat(a.getCodSubmercado()).as("check codSubmercado").isEqualTo(expected.getCodSubmercado()))
            .satisfies(a -> assertThat(a.getSglTipousina()).as("check sglTipousina").isEqualTo(expected.getSglTipousina()))
            .satisfies(a -> assertThat(a.getCodUsinapdp()).as("check codUsinapdp").isEqualTo(expected.getCodUsinapdp()))
            .satisfies(a -> assertThat(a.getNomUsinapdp()).as("check nomUsinapdp").isEqualTo(expected.getNomUsinapdp()))
            .satisfies(a -> assertThat(a.getNumIntdespa()).as("check numIntdespa").isEqualTo(expected.getNumIntdespa()))
            .satisfies(a -> assertThat(a.getValDespasup()).as("check valDespasup").isEqualTo(expected.getValDespasup()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024EntityUpdatableRelationshipsEquals(
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity expected,
        OnsDadosHistoricoDespachoEnergiaJaneiro2021ASetembro2024Entity actual
    ) {
        // empty method
    }
}
