package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosProgramadosElementosFluxoControladoEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosProgramadosElementosFluxoControladoEntityAllPropertiesEquals(
        OnsDadosProgramadosElementosFluxoControladoEntity expected,
        OnsDadosProgramadosElementosFluxoControladoEntity actual
    ) {
        assertOnsDadosProgramadosElementosFluxoControladoEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosProgramadosElementosFluxoControladoEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosProgramadosElementosFluxoControladoEntityAllUpdatablePropertiesEquals(
        OnsDadosProgramadosElementosFluxoControladoEntity expected,
        OnsDadosProgramadosElementosFluxoControladoEntity actual
    ) {
        assertOnsDadosProgramadosElementosFluxoControladoEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosProgramadosElementosFluxoControladoEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosProgramadosElementosFluxoControladoEntityAutoGeneratedPropertiesEquals(
        OnsDadosProgramadosElementosFluxoControladoEntity expected,
        OnsDadosProgramadosElementosFluxoControladoEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosProgramadosElementosFluxoControladoEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosProgramadosElementosFluxoControladoEntityUpdatableFieldsEquals(
        OnsDadosProgramadosElementosFluxoControladoEntity expected,
        OnsDadosProgramadosElementosFluxoControladoEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosProgramadosElementosFluxoControladoEntity relevant properties")
            .satisfies(a -> assertThat(a.getDinProgramacaodia()).as("check dinProgramacaodia").isEqualTo(expected.getDinProgramacaodia()))
            .satisfies(a -> assertThat(a.getNumPatamar()).as("check numPatamar").isEqualTo(expected.getNumPatamar()))
            .satisfies(a ->
                assertThat(a.getNomElementofluxocontrolado())
                    .as("check nomElementofluxocontrolado")
                    .isEqualTo(expected.getNomElementofluxocontrolado())
            )
            .satisfies(a ->
                assertThat(a.getDscElementofluxocontrolado())
                    .as("check dscElementofluxocontrolado")
                    .isEqualTo(expected.getDscElementofluxocontrolado())
            )
            .satisfies(a -> assertThat(a.getTipTerminal()).as("check tipTerminal").isEqualTo(expected.getTipTerminal()))
            .satisfies(a -> assertThat(a.getCodSubmercado()).as("check codSubmercado").isEqualTo(expected.getCodSubmercado()))
            .satisfies(a -> assertThat(a.getValCarga()).as("check valCarga").isEqualTo(expected.getValCarga()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosProgramadosElementosFluxoControladoEntityUpdatableRelationshipsEquals(
        OnsDadosProgramadosElementosFluxoControladoEntity expected,
        OnsDadosProgramadosElementosFluxoControladoEntity actual
    ) {
        // empty method
    }
}
