package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsDadosIntercambioEnergiaModalidadeEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIntercambioEnergiaModalidadeEntityAllPropertiesEquals(
        OnsDadosIntercambioEnergiaModalidadeEntity expected,
        OnsDadosIntercambioEnergiaModalidadeEntity actual
    ) {
        assertOnsDadosIntercambioEnergiaModalidadeEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsDadosIntercambioEnergiaModalidadeEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIntercambioEnergiaModalidadeEntityAllUpdatablePropertiesEquals(
        OnsDadosIntercambioEnergiaModalidadeEntity expected,
        OnsDadosIntercambioEnergiaModalidadeEntity actual
    ) {
        assertOnsDadosIntercambioEnergiaModalidadeEntityUpdatableFieldsEquals(expected, actual);
        assertOnsDadosIntercambioEnergiaModalidadeEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIntercambioEnergiaModalidadeEntityAutoGeneratedPropertiesEquals(
        OnsDadosIntercambioEnergiaModalidadeEntity expected,
        OnsDadosIntercambioEnergiaModalidadeEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosIntercambioEnergiaModalidadeEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIntercambioEnergiaModalidadeEntityUpdatableFieldsEquals(
        OnsDadosIntercambioEnergiaModalidadeEntity expected,
        OnsDadosIntercambioEnergiaModalidadeEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsDadosIntercambioEnergiaModalidadeEntity relevant properties")
            .satisfies(a -> assertThat(a.getNomConversora()).as("check nomConversora").isEqualTo(expected.getNomConversora()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a ->
                assertThat(a.getValModalidadecontratual())
                    .as("check valModalidadecontratual")
                    .isEqualTo(expected.getValModalidadecontratual())
            )
            .satisfies(a ->
                assertThat(a.getValModalidadeemergencial())
                    .as("check valModalidadeemergencial")
                    .isEqualTo(expected.getValModalidadeemergencial())
            )
            .satisfies(a ->
                assertThat(a.getValModalidadeoportunidade())
                    .as("check valModalidadeoportunidade")
                    .isEqualTo(expected.getValModalidadeoportunidade())
            )
            .satisfies(a -> assertThat(a.getValModalidadeteste()).as("check valModalidadeteste").isEqualTo(expected.getValModalidadeteste())
            )
            .satisfies(a ->
                assertThat(a.getValModalidadeexcepcional())
                    .as("check valModalidadeexcepcional")
                    .isEqualTo(expected.getValModalidadeexcepcional())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsDadosIntercambioEnergiaModalidadeEntityUpdatableRelationshipsEquals(
        OnsDadosIntercambioEnergiaModalidadeEntity expected,
        OnsDadosIntercambioEnergiaModalidadeEntity actual
    ) {
        // empty method
    }
}
