package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsEarDiarioSubsistemaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioSubsistemaEntityAllPropertiesEquals(
        OnsEarDiarioSubsistemaEntity expected,
        OnsEarDiarioSubsistemaEntity actual
    ) {
        assertOnsEarDiarioSubsistemaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsEarDiarioSubsistemaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioSubsistemaEntityAllUpdatablePropertiesEquals(
        OnsEarDiarioSubsistemaEntity expected,
        OnsEarDiarioSubsistemaEntity actual
    ) {
        assertOnsEarDiarioSubsistemaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsEarDiarioSubsistemaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioSubsistemaEntityAutoGeneratedPropertiesEquals(
        OnsEarDiarioSubsistemaEntity expected,
        OnsEarDiarioSubsistemaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEarDiarioSubsistemaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioSubsistemaEntityUpdatableFieldsEquals(
        OnsEarDiarioSubsistemaEntity expected,
        OnsEarDiarioSubsistemaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEarDiarioSubsistemaEntity relevant properties")
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getEarData()).as("check earData").isEqualTo(expected.getEarData()))
            .satisfies(a -> assertThat(a.getEarMaxSubsistema()).as("check earMaxSubsistema").isEqualTo(expected.getEarMaxSubsistema()))
            .satisfies(a ->
                assertThat(a.getEarVerifSubsistemaMwmes())
                    .as("check earVerifSubsistemaMwmes")
                    .isEqualTo(expected.getEarVerifSubsistemaMwmes())
            )
            .satisfies(a ->
                assertThat(a.getEarVerifSubsistemaPercentual())
                    .as("check earVerifSubsistemaPercentual")
                    .isEqualTo(expected.getEarVerifSubsistemaPercentual())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioSubsistemaEntityUpdatableRelationshipsEquals(
        OnsEarDiarioSubsistemaEntity expected,
        OnsEarDiarioSubsistemaEntity actual
    ) {
        // empty method
    }
}
