package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsEnaDiarioSubsistemaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioSubsistemaEntityAllPropertiesEquals(
        OnsEnaDiarioSubsistemaEntity expected,
        OnsEnaDiarioSubsistemaEntity actual
    ) {
        assertOnsEnaDiarioSubsistemaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsEnaDiarioSubsistemaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioSubsistemaEntityAllUpdatablePropertiesEquals(
        OnsEnaDiarioSubsistemaEntity expected,
        OnsEnaDiarioSubsistemaEntity actual
    ) {
        assertOnsEnaDiarioSubsistemaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsEnaDiarioSubsistemaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioSubsistemaEntityAutoGeneratedPropertiesEquals(
        OnsEnaDiarioSubsistemaEntity expected,
        OnsEnaDiarioSubsistemaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEnaDiarioSubsistemaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioSubsistemaEntityUpdatableFieldsEquals(
        OnsEnaDiarioSubsistemaEntity expected,
        OnsEnaDiarioSubsistemaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEnaDiarioSubsistemaEntity relevant properties")
            .satisfies(a ->
                assertThat(a.getEnaArmazenavelRegiaoPercentualmlt())
                    .as("check enaArmazenavelRegiaoPercentualmlt")
                    .isEqualTo(expected.getEnaArmazenavelRegiaoPercentualmlt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioSubsistemaEntityUpdatableRelationshipsEquals(
        OnsEnaDiarioSubsistemaEntity expected,
        OnsEnaDiarioSubsistemaEntity actual
    ) {
        // empty method
    }
}
