package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsEnaDiarioBaciaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioBaciaEntityAllPropertiesEquals(OnsEnaDiarioBaciaEntity expected, OnsEnaDiarioBaciaEntity actual) {
        assertOnsEnaDiarioBaciaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsEnaDiarioBaciaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioBaciaEntityAllUpdatablePropertiesEquals(
        OnsEnaDiarioBaciaEntity expected,
        OnsEnaDiarioBaciaEntity actual
    ) {
        assertOnsEnaDiarioBaciaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsEnaDiarioBaciaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioBaciaEntityAutoGeneratedPropertiesEquals(
        OnsEnaDiarioBaciaEntity expected,
        OnsEnaDiarioBaciaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEnaDiarioBaciaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioBaciaEntityUpdatableFieldsEquals(
        OnsEnaDiarioBaciaEntity expected,
        OnsEnaDiarioBaciaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEnaDiarioBaciaEntity relevant properties")
            .satisfies(a ->
                assertThat(a.getEnaArmazenavelBaciaPercentualmlt())
                    .as("check enaArmazenavelBaciaPercentualmlt")
                    .isEqualTo(expected.getEnaArmazenavelBaciaPercentualmlt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioBaciaEntityUpdatableRelationshipsEquals(
        OnsEnaDiarioBaciaEntity expected,
        OnsEnaDiarioBaciaEntity actual
    ) {
        // empty method
    }
}
