package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsEnaDiarioReservatorioEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioReservatorioEntityAllPropertiesEquals(
        OnsEnaDiarioReservatorioEntity expected,
        OnsEnaDiarioReservatorioEntity actual
    ) {
        assertOnsEnaDiarioReservatorioEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsEnaDiarioReservatorioEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioReservatorioEntityAllUpdatablePropertiesEquals(
        OnsEnaDiarioReservatorioEntity expected,
        OnsEnaDiarioReservatorioEntity actual
    ) {
        assertOnsEnaDiarioReservatorioEntityUpdatableFieldsEquals(expected, actual);
        assertOnsEnaDiarioReservatorioEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioReservatorioEntityAutoGeneratedPropertiesEquals(
        OnsEnaDiarioReservatorioEntity expected,
        OnsEnaDiarioReservatorioEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEnaDiarioReservatorioEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioReservatorioEntityUpdatableFieldsEquals(
        OnsEnaDiarioReservatorioEntity expected,
        OnsEnaDiarioReservatorioEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEnaDiarioReservatorioEntity relevant properties")
            .satisfies(a -> assertThat(a.getEnaBrutaResMwmed()).as("check enaBrutaResMwmed").isEqualTo(expected.getEnaBrutaResMwmed()))
            .satisfies(a ->
                assertThat(a.getEnaBrutaResPercentualmlt())
                    .as("check enaBrutaResPercentualmlt")
                    .isEqualTo(expected.getEnaBrutaResPercentualmlt())
            )
            .satisfies(a ->
                assertThat(a.getEnaArmazenavelResMwmed()).as("check enaArmazenavelResMwmed").isEqualTo(expected.getEnaArmazenavelResMwmed())
            )
            .satisfies(a ->
                assertThat(a.getEnaArmazenavelResPercentualmlt())
                    .as("check enaArmazenavelResPercentualmlt")
                    .isEqualTo(expected.getEnaArmazenavelResPercentualmlt())
            )
            .satisfies(a -> assertThat(a.getEnaQuedaBruta()).as("check enaQuedaBruta").isEqualTo(expected.getEnaQuedaBruta()))
            .satisfies(a -> assertThat(a.getMltEna()).as("check mltEna").isEqualTo(expected.getMltEna()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEnaDiarioReservatorioEntityUpdatableRelationshipsEquals(
        OnsEnaDiarioReservatorioEntity expected,
        OnsEnaDiarioReservatorioEntity actual
    ) {
        // empty method
    }
}
