package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsEarDiarioReservatorioEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReservatorioEntityAllPropertiesEquals(
        OnsEarDiarioReservatorioEntity expected,
        OnsEarDiarioReservatorioEntity actual
    ) {
        assertOnsEarDiarioReservatorioEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsEarDiarioReservatorioEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReservatorioEntityAllUpdatablePropertiesEquals(
        OnsEarDiarioReservatorioEntity expected,
        OnsEarDiarioReservatorioEntity actual
    ) {
        assertOnsEarDiarioReservatorioEntityUpdatableFieldsEquals(expected, actual);
        assertOnsEarDiarioReservatorioEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReservatorioEntityAutoGeneratedPropertiesEquals(
        OnsEarDiarioReservatorioEntity expected,
        OnsEarDiarioReservatorioEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEarDiarioReservatorioEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReservatorioEntityUpdatableFieldsEquals(
        OnsEarDiarioReservatorioEntity expected,
        OnsEarDiarioReservatorioEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEarDiarioReservatorioEntity relevant properties")
            .satisfies(a ->
                assertThat(a.getIdSubsistemaJusante()).as("check idSubsistemaJusante").isEqualTo(expected.getIdSubsistemaJusante())
            )
            .satisfies(a ->
                assertThat(a.getNomSubsistemaJusante()).as("check nomSubsistemaJusante").isEqualTo(expected.getNomSubsistemaJusante())
            )
            .satisfies(a -> assertThat(a.getEarData()).as("check earData").isEqualTo(expected.getEarData()))
            .satisfies(a ->
                assertThat(a.getEarReservatorioSubsistemaProprioMwmes())
                    .as("check earReservatorioSubsistemaProprioMwmes")
                    .isEqualTo(expected.getEarReservatorioSubsistemaProprioMwmes())
            )
            .satisfies(a ->
                assertThat(a.getEarReservatorioSubsistemaJusanteMwmes())
                    .as("check earReservatorioSubsistemaJusanteMwmes")
                    .isEqualTo(expected.getEarReservatorioSubsistemaJusanteMwmes())
            )
            .satisfies(a ->
                assertThat(a.getEarmaxReservatorioSubsistemaProprioMwmes())
                    .as("check earmaxReservatorioSubsistemaProprioMwmes")
                    .isEqualTo(expected.getEarmaxReservatorioSubsistemaProprioMwmes())
            )
            .satisfies(a ->
                assertThat(a.getEarmaxReservatorioSubsistemaJusanteMwmes())
                    .as("check earmaxReservatorioSubsistemaJusanteMwmes")
                    .isEqualTo(expected.getEarmaxReservatorioSubsistemaJusanteMwmes())
            )
            .satisfies(a ->
                assertThat(a.getEarReservatorioPercentual())
                    .as("check earReservatorioPercentual")
                    .isEqualTo(expected.getEarReservatorioPercentual())
            )
            .satisfies(a -> assertThat(a.getEarTotalMwmes()).as("check earTotalMwmes").isEqualTo(expected.getEarTotalMwmes()))
            .satisfies(a ->
                assertThat(a.getEarMaximaTotalMwmes()).as("check earMaximaTotalMwmes").isEqualTo(expected.getEarMaximaTotalMwmes())
            )
            .satisfies(a -> assertThat(a.getValContribearbacia()).as("check valContribearbacia").isEqualTo(expected.getValContribearbacia())
            )
            .satisfies(a ->
                assertThat(a.getValContribearmaxbacia()).as("check valContribearmaxbacia").isEqualTo(expected.getValContribearmaxbacia())
            )
            .satisfies(a ->
                assertThat(a.getValContribearsubsistema())
                    .as("check valContribearsubsistema")
                    .isEqualTo(expected.getValContribearsubsistema())
            )
            .satisfies(a ->
                assertThat(a.getValContribearmaxsubsistema())
                    .as("check valContribearmaxsubsistema")
                    .isEqualTo(expected.getValContribearmaxsubsistema())
            )
            .satisfies(a ->
                assertThat(a.getValContribearsubsistemajusante())
                    .as("check valContribearsubsistemajusante")
                    .isEqualTo(expected.getValContribearsubsistemajusante())
            )
            .satisfies(a ->
                assertThat(a.getValContribearmaxsubsistemajusante())
                    .as("check valContribearmaxsubsistemajusante")
                    .isEqualTo(expected.getValContribearmaxsubsistemajusante())
            )
            .satisfies(a -> assertThat(a.getValContribearsin()).as("check valContribearsin").isEqualTo(expected.getValContribearsin()))
            .satisfies(a ->
                assertThat(a.getValContribearmaxsin()).as("check valContribearmaxsin").isEqualTo(expected.getValContribearmaxsin())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReservatorioEntityUpdatableRelationshipsEquals(
        OnsEarDiarioReservatorioEntity expected,
        OnsEarDiarioReservatorioEntity actual
    ) {
        // empty method
    }
}
