package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsEarDiarioReeReservatorioEquivalenteEnergiaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityAllPropertiesEquals(
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity expected,
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity actual
    ) {
        assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityAllUpdatablePropertiesEquals(
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity expected,
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity actual
    ) {
        assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityAutoGeneratedPropertiesEquals(
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity expected,
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityUpdatableFieldsEquals(
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity expected,
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity relevant properties")
            .satisfies(a -> assertThat(a.getNomRee()).as("check nomRee").isEqualTo(expected.getNomRee()))
            .satisfies(a -> assertThat(a.getEarData()).as("check earData").isEqualTo(expected.getEarData()))
            .satisfies(a -> assertThat(a.getEarMaxRee()).as("check earMaxRee").isEqualTo(expected.getEarMaxRee()))
            .satisfies(a -> assertThat(a.getEarVerifReeMwmes()).as("check earVerifReeMwmes").isEqualTo(expected.getEarVerifReeMwmes()))
            .satisfies(a ->
                assertThat(a.getEarVerifReePercentual()).as("check earVerifReePercentual").isEqualTo(expected.getEarVerifReePercentual())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsEarDiarioReeReservatorioEquivalenteEnergiaEntityUpdatableRelationshipsEquals(
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity expected,
        OnsEarDiarioReeReservatorioEquivalenteEnergiaEntity actual
    ) {
        // empty method
    }
}
