package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsGeracaoUsinaEmBaseHorariaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoUsinaEmBaseHorariaEntityAllPropertiesEquals(
        OnsGeracaoUsinaEmBaseHorariaEntity expected,
        OnsGeracaoUsinaEmBaseHorariaEntity actual
    ) {
        assertOnsGeracaoUsinaEmBaseHorariaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsGeracaoUsinaEmBaseHorariaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoUsinaEmBaseHorariaEntityAllUpdatablePropertiesEquals(
        OnsGeracaoUsinaEmBaseHorariaEntity expected,
        OnsGeracaoUsinaEmBaseHorariaEntity actual
    ) {
        assertOnsGeracaoUsinaEmBaseHorariaEntityUpdatableFieldsEquals(expected, actual);
        assertOnsGeracaoUsinaEmBaseHorariaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoUsinaEmBaseHorariaEntityAutoGeneratedPropertiesEquals(
        OnsGeracaoUsinaEmBaseHorariaEntity expected,
        OnsGeracaoUsinaEmBaseHorariaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsGeracaoUsinaEmBaseHorariaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoUsinaEmBaseHorariaEntityUpdatableFieldsEquals(
        OnsGeracaoUsinaEmBaseHorariaEntity expected,
        OnsGeracaoUsinaEmBaseHorariaEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsGeracaoUsinaEmBaseHorariaEntity relevant properties")
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getIdSubsistema()).as("check idSubsistema").isEqualTo(expected.getIdSubsistema()))
            .satisfies(a -> assertThat(a.getNomSubsistema()).as("check nomSubsistema").isEqualTo(expected.getNomSubsistema()))
            .satisfies(a -> assertThat(a.getIdEstado()).as("check idEstado").isEqualTo(expected.getIdEstado()))
            .satisfies(a -> assertThat(a.getNomEstado()).as("check nomEstado").isEqualTo(expected.getNomEstado()))
            .satisfies(a ->
                assertThat(a.getCodModalidadeoperacao()).as("check codModalidadeoperacao").isEqualTo(expected.getCodModalidadeoperacao())
            )
            .satisfies(a -> assertThat(a.getNomTipousina()).as("check nomTipousina").isEqualTo(expected.getNomTipousina()))
            .satisfies(a -> assertThat(a.getNomTipocombustivel()).as("check nomTipocombustivel").isEqualTo(expected.getNomTipocombustivel())
            )
            .satisfies(a -> assertThat(a.getNomUsina()).as("check nomUsina").isEqualTo(expected.getNomUsina()))
            .satisfies(a -> assertThat(a.getIdOns()).as("check idOns").isEqualTo(expected.getIdOns()))
            .satisfies(a -> assertThat(a.getCeg()).as("check ceg").isEqualTo(expected.getCeg()))
            .satisfies(a -> assertThat(a.getValGeracao()).as("check valGeracao").isEqualTo(expected.getValGeracao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoUsinaEmBaseHorariaEntityUpdatableRelationshipsEquals(
        OnsGeracaoUsinaEmBaseHorariaEntity expected,
        OnsGeracaoUsinaEmBaseHorariaEntity actual
    ) {
        // empty method
    }
}
