package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsGeracaoComercialParaExportacaoInternacionalEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoComercialParaExportacaoInternacionalEntityAllPropertiesEquals(
        OnsGeracaoComercialParaExportacaoInternacionalEntity expected,
        OnsGeracaoComercialParaExportacaoInternacionalEntity actual
    ) {
        assertOnsGeracaoComercialParaExportacaoInternacionalEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsGeracaoComercialParaExportacaoInternacionalEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoComercialParaExportacaoInternacionalEntityAllUpdatablePropertiesEquals(
        OnsGeracaoComercialParaExportacaoInternacionalEntity expected,
        OnsGeracaoComercialParaExportacaoInternacionalEntity actual
    ) {
        assertOnsGeracaoComercialParaExportacaoInternacionalEntityUpdatableFieldsEquals(expected, actual);
        assertOnsGeracaoComercialParaExportacaoInternacionalEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoComercialParaExportacaoInternacionalEntityAutoGeneratedPropertiesEquals(
        OnsGeracaoComercialParaExportacaoInternacionalEntity expected,
        OnsGeracaoComercialParaExportacaoInternacionalEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsGeracaoComercialParaExportacaoInternacionalEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoComercialParaExportacaoInternacionalEntityUpdatableFieldsEquals(
        OnsGeracaoComercialParaExportacaoInternacionalEntity expected,
        OnsGeracaoComercialParaExportacaoInternacionalEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsGeracaoComercialParaExportacaoInternacionalEntity relevant properties")
            .satisfies(a -> assertThat(a.getNomConversora()).as("check nomConversora").isEqualTo(expected.getNomConversora()))
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a ->
                assertThat(a.getValModalidadecontratual())
                    .as("check valModalidadecontratual")
                    .isEqualTo(expected.getValModalidadecontratual())
            )
            .satisfies(a ->
                assertThat(a.getValModalidadeemergencial())
                    .as("check valModalidadeemergencial")
                    .isEqualTo(expected.getValModalidadeemergencial())
            )
            .satisfies(a ->
                assertThat(a.getValModalidadeoportunidade())
                    .as("check valModalidadeoportunidade")
                    .isEqualTo(expected.getValModalidadeoportunidade())
            )
            .satisfies(a -> assertThat(a.getValModalidadeteste()).as("check valModalidadeteste").isEqualTo(expected.getValModalidadeteste())
            )
            .satisfies(a ->
                assertThat(a.getValModalidadeexcepcional())
                    .as("check valModalidadeexcepcional")
                    .isEqualTo(expected.getValModalidadeexcepcional())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsGeracaoComercialParaExportacaoInternacionalEntityUpdatableRelationshipsEquals(
        OnsGeracaoComercialParaExportacaoInternacionalEntity expected,
        OnsGeracaoComercialParaExportacaoInternacionalEntity actual
    ) {
        // empty method
    }
}
