package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsIntercambioSinComOutrosPaisesEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambioSinComOutrosPaisesEntityAllPropertiesEquals(
        OnsIntercambioSinComOutrosPaisesEntity expected,
        OnsIntercambioSinComOutrosPaisesEntity actual
    ) {
        assertOnsIntercambioSinComOutrosPaisesEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsIntercambioSinComOutrosPaisesEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambioSinComOutrosPaisesEntityAllUpdatablePropertiesEquals(
        OnsIntercambioSinComOutrosPaisesEntity expected,
        OnsIntercambioSinComOutrosPaisesEntity actual
    ) {
        assertOnsIntercambioSinComOutrosPaisesEntityUpdatableFieldsEquals(expected, actual);
        assertOnsIntercambioSinComOutrosPaisesEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambioSinComOutrosPaisesEntityAutoGeneratedPropertiesEquals(
        OnsIntercambioSinComOutrosPaisesEntity expected,
        OnsIntercambioSinComOutrosPaisesEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIntercambioSinComOutrosPaisesEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambioSinComOutrosPaisesEntityUpdatableFieldsEquals(
        OnsIntercambioSinComOutrosPaisesEntity expected,
        OnsIntercambioSinComOutrosPaisesEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIntercambioSinComOutrosPaisesEntity relevant properties")
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getNomPaisdestino()).as("check nomPaisdestino").isEqualTo(expected.getNomPaisdestino()))
            .satisfies(a ->
                assertThat(a.getValIntercambiomwmed()).as("check valIntercambiomwmed").isEqualTo(expected.getValIntercambiomwmed())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambioSinComOutrosPaisesEntityUpdatableRelationshipsEquals(
        OnsIntercambioSinComOutrosPaisesEntity expected,
        OnsIntercambioSinComOutrosPaisesEntity actual
    ) {
        // empty method
    }
}
