package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityAllPropertiesEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity actual
    ) {
        assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityAllUpdatablePropertiesEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity actual
    ) {
        assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityUpdatableFieldsEquals(expected, actual);
        assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityAutoGeneratedPropertiesEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityUpdatableFieldsEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity relevant properties")
            .satisfies(a -> assertThat(a.getDscAgregacao()).as("check dscAgregacao").isEqualTo(expected.getDscAgregacao()))
            .satisfies(a -> assertThat(a.getCodCaracteristica()).as("check codCaracteristica").isEqualTo(expected.getCodCaracteristica()))
            .satisfies(a -> assertThat(a.getDscCaracteristica()).as("check dscCaracteristica").isEqualTo(expected.getDscCaracteristica()))
            .satisfies(a -> assertThat(a.getIdPeriodicidade()).as("check idPeriodicidade").isEqualTo(expected.getIdPeriodicidade()))
            .satisfies(a -> assertThat(a.getDinReferencia()).as("check dinReferencia").isEqualTo(expected.getDinReferencia()))
            .satisfies(a -> assertThat(a.getValCiper1()).as("check valCiper1").isEqualTo(expected.getValCiper1()))
            .satisfies(a -> assertThat(a.getValCiper2()).as("check valCiper2").isEqualTo(expected.getValCiper2()))
            .satisfies(a -> assertThat(a.getValCiper3()).as("check valCiper3").isEqualTo(expected.getValCiper3()))
            .satisfies(a -> assertThat(a.getValCiper4()).as("check valCiper4").isEqualTo(expected.getValCiper4()))
            .satisfies(a -> assertThat(a.getValCiper5()).as("check valCiper5").isEqualTo(expected.getValCiper5()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntityUpdatableRelationshipsEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaCiperCargaInterrompidaPerturbacoesEntity actual
    ) {
        // empty method
    }
}
