package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsIntercambiosEntreSubsistemasEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambiosEntreSubsistemasEntityAllPropertiesEquals(
        OnsIntercambiosEntreSubsistemasEntity expected,
        OnsIntercambiosEntreSubsistemasEntity actual
    ) {
        assertOnsIntercambiosEntreSubsistemasEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsIntercambiosEntreSubsistemasEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambiosEntreSubsistemasEntityAllUpdatablePropertiesEquals(
        OnsIntercambiosEntreSubsistemasEntity expected,
        OnsIntercambiosEntreSubsistemasEntity actual
    ) {
        assertOnsIntercambiosEntreSubsistemasEntityUpdatableFieldsEquals(expected, actual);
        assertOnsIntercambiosEntreSubsistemasEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambiosEntreSubsistemasEntityAutoGeneratedPropertiesEquals(
        OnsIntercambiosEntreSubsistemasEntity expected,
        OnsIntercambiosEntreSubsistemasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIntercambiosEntreSubsistemasEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambiosEntreSubsistemasEntityUpdatableFieldsEquals(
        OnsIntercambiosEntreSubsistemasEntity expected,
        OnsIntercambiosEntreSubsistemasEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIntercambiosEntreSubsistemasEntity relevant properties")
            .satisfies(a -> assertThat(a.getDinInstante()).as("check dinInstante").isEqualTo(expected.getDinInstante()))
            .satisfies(a -> assertThat(a.getIdSubsistemaOrigem()).as("check idSubsistemaOrigem").isEqualTo(expected.getIdSubsistemaOrigem())
            )
            .satisfies(a ->
                assertThat(a.getNomSubsistemaOrigem()).as("check nomSubsistemaOrigem").isEqualTo(expected.getNomSubsistemaOrigem())
            )
            .satisfies(a ->
                assertThat(a.getIdSubsistemaDestino()).as("check idSubsistemaDestino").isEqualTo(expected.getIdSubsistemaDestino())
            )
            .satisfies(a ->
                assertThat(a.getNomSubsistemaDestino()).as("check nomSubsistemaDestino").isEqualTo(expected.getNomSubsistemaDestino())
            )
            .satisfies(a ->
                assertThat(a.getValIntercambiomwmed()).as("check valIntercambiomwmed").isEqualTo(expected.getValIntercambiomwmed())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIntercambiosEntreSubsistemasEntityUpdatableRelationshipsEquals(
        OnsIntercambiosEntreSubsistemasEntity expected,
        OnsIntercambiosEntreSubsistemasEntity actual
    ) {
        // empty method
    }
}
