package com.alexandrebfreitas.wue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityAllPropertiesEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity actual
    ) {
        assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityAllUpdatablePropertiesEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity actual
    ) {
        assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityUpdatableFieldsEquals(expected, actual);
        assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityAutoGeneratedPropertiesEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityUpdatableFieldsEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity actual
    ) {
        assertThat(actual)
            .as("Verify OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity relevant properties")
            .satisfies(a -> assertThat(a.getCodIndicador()).as("check codIndicador").isEqualTo(expected.getCodIndicador()))
            .satisfies(a -> assertThat(a.getDscAgregacao()).as("check dscAgregacao").isEqualTo(expected.getDscAgregacao()))
            .satisfies(a -> assertThat(a.getCodCaracteristica()).as("check codCaracteristica").isEqualTo(expected.getCodCaracteristica()))
            .satisfies(a -> assertThat(a.getDscCaracteristica()).as("check dscCaracteristica").isEqualTo(expected.getDscCaracteristica()))
            .satisfies(a -> assertThat(a.getIdPeriodicidade()).as("check idPeriodicidade").isEqualTo(expected.getIdPeriodicidade()))
            .satisfies(a -> assertThat(a.getDinReferencia()).as("check dinReferencia").isEqualTo(expected.getDinReferencia()))
            .satisfies(a -> assertThat(a.getValIndicador()).as("check valIndicador").isEqualTo(expected.getValIndicador()))
            .satisfies(a -> assertThat(a.getNumPerturbacoes()).as("check numPerturbacoes").isEqualTo(expected.getNumPerturbacoes()))
            .satisfies(a ->
                assertThat(a.getNumPerturbacoescortecarga())
                    .as("check numPerturbacoescortecarga")
                    .isEqualTo(expected.getNumPerturbacoescortecarga())
            )
            .satisfies(a ->
                assertThat(a.getNumPerturbacoescortecarga0a50mw())
                    .as("check numPerturbacoescortecarga0a50mw")
                    .isEqualTo(expected.getNumPerturbacoescortecarga0a50mw())
            )
            .satisfies(a ->
                assertThat(a.getNumPerturbacoescortecarga50a100mw())
                    .as("check numPerturbacoescortecarga50a100mw")
                    .isEqualTo(expected.getNumPerturbacoescortecarga50a100mw())
            )
            .satisfies(a ->
                assertThat(a.getNumPerturbacoescortecargaMaior100mw())
                    .as("check numPerturbacoescortecargaMaior100mw")
                    .isEqualTo(expected.getNumPerturbacoescortecargaMaior100mw())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntityUpdatableRelationshipsEquals(
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity expected,
        OnsIndicadoresConfiabilidadeRedeBasicaRobustezRmalRmcsRrbERrbcsEntity actual
    ) {
        // empty method
    }
}
